/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutAuthIndexRouteImport } from './routes/_layout/auth/index'
import { Route as LayoutAuthenticatedMockInterviewIndexRouteImport } from './routes/_layout/_authenticated/mock-interview/index'
import { Route as LayoutAuthenticatedDashboardIndexRouteImport } from './routes/_layout/_authenticated/dashboard/index'
import { Route as LayoutAuthenticatedCommunityIndexRouteImport } from './routes/_layout/_authenticated/community/index'
import { Route as LayoutAuthenticatedAnalyzeIndexRouteImport } from './routes/_layout/_authenticated/analyze/index'
import { Route as LayoutAuthenticatedAnalyzeResultsResultIdRouteImport } from './routes/_layout/_authenticated/analyze/results/$resultId'
import { Route as LayoutAuthenticatedMockInterviewSessionsSessionIdIndexRouteImport } from './routes/_layout/_authenticated/mock-interview/sessions/$sessionId/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthIndexRoute = LayoutAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedMockInterviewIndexRoute =
  LayoutAuthenticatedMockInterviewIndexRouteImport.update({
    id: '/mock-interview/',
    path: '/mock-interview/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDashboardIndexRoute =
  LayoutAuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedCommunityIndexRoute =
  LayoutAuthenticatedCommunityIndexRouteImport.update({
    id: '/community/',
    path: '/community/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAnalyzeIndexRoute =
  LayoutAuthenticatedAnalyzeIndexRouteImport.update({
    id: '/analyze/',
    path: '/analyze/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAnalyzeResultsResultIdRoute =
  LayoutAuthenticatedAnalyzeResultsResultIdRouteImport.update({
    id: '/analyze/results/$resultId',
    path: '/analyze/results/$resultId',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedMockInterviewSessionsSessionIdIndexRoute =
  LayoutAuthenticatedMockInterviewSessionsSessionIdIndexRouteImport.update({
    id: '/mock-interview/sessions/$sessionId/',
    path: '/mock-interview/sessions/$sessionId/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/auth/': typeof LayoutAuthIndexRoute
  '/analyze/': typeof LayoutAuthenticatedAnalyzeIndexRoute
  '/community/': typeof LayoutAuthenticatedCommunityIndexRoute
  '/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/mock-interview/': typeof LayoutAuthenticatedMockInterviewIndexRoute
  '/analyze/results/$resultId': typeof LayoutAuthenticatedAnalyzeResultsResultIdRoute
  '/mock-interview/sessions/$sessionId/': typeof LayoutAuthenticatedMockInterviewSessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/auth': typeof LayoutAuthIndexRoute
  '/analyze': typeof LayoutAuthenticatedAnalyzeIndexRoute
  '/community': typeof LayoutAuthenticatedCommunityIndexRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardIndexRoute
  '/mock-interview': typeof LayoutAuthenticatedMockInterviewIndexRoute
  '/analyze/results/$resultId': typeof LayoutAuthenticatedAnalyzeResultsResultIdRoute
  '/mock-interview/sessions/$sessionId': typeof LayoutAuthenticatedMockInterviewSessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/auth/': typeof LayoutAuthIndexRoute
  '/_layout/_authenticated/analyze/': typeof LayoutAuthenticatedAnalyzeIndexRoute
  '/_layout/_authenticated/community/': typeof LayoutAuthenticatedCommunityIndexRoute
  '/_layout/_authenticated/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/_layout/_authenticated/mock-interview/': typeof LayoutAuthenticatedMockInterviewIndexRoute
  '/_layout/_authenticated/analyze/results/$resultId': typeof LayoutAuthenticatedAnalyzeResultsResultIdRoute
  '/_layout/_authenticated/mock-interview/sessions/$sessionId/': typeof LayoutAuthenticatedMockInterviewSessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/'
    | '/analyze/'
    | '/community/'
    | '/dashboard/'
    | '/mock-interview/'
    | '/analyze/results/$resultId'
    | '/mock-interview/sessions/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analyze'
    | '/community'
    | '/dashboard'
    | '/mock-interview'
    | '/analyze/results/$resultId'
    | '/mock-interview/sessions/$sessionId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_authenticated'
    | '/_layout/'
    | '/_layout/auth/'
    | '/_layout/_authenticated/analyze/'
    | '/_layout/_authenticated/community/'
    | '/_layout/_authenticated/dashboard/'
    | '/_layout/_authenticated/mock-interview/'
    | '/_layout/_authenticated/analyze/results/$resultId'
    | '/_layout/_authenticated/mock-interview/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/auth/': {
      id: '/_layout/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof LayoutAuthIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/mock-interview/': {
      id: '/_layout/_authenticated/mock-interview/'
      path: '/mock-interview'
      fullPath: '/mock-interview/'
      preLoaderRoute: typeof LayoutAuthenticatedMockInterviewIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/dashboard/': {
      id: '/_layout/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/community/': {
      id: '/_layout/_authenticated/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof LayoutAuthenticatedCommunityIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/analyze/': {
      id: '/_layout/_authenticated/analyze/'
      path: '/analyze'
      fullPath: '/analyze/'
      preLoaderRoute: typeof LayoutAuthenticatedAnalyzeIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/analyze/results/$resultId': {
      id: '/_layout/_authenticated/analyze/results/$resultId'
      path: '/analyze/results/$resultId'
      fullPath: '/analyze/results/$resultId'
      preLoaderRoute: typeof LayoutAuthenticatedAnalyzeResultsResultIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/mock-interview/sessions/$sessionId/': {
      id: '/_layout/_authenticated/mock-interview/sessions/$sessionId/'
      path: '/mock-interview/sessions/$sessionId'
      fullPath: '/mock-interview/sessions/$sessionId/'
      preLoaderRoute: typeof LayoutAuthenticatedMockInterviewSessionsSessionIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
  }
}

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedAnalyzeIndexRoute: typeof LayoutAuthenticatedAnalyzeIndexRoute
  LayoutAuthenticatedCommunityIndexRoute: typeof LayoutAuthenticatedCommunityIndexRoute
  LayoutAuthenticatedDashboardIndexRoute: typeof LayoutAuthenticatedDashboardIndexRoute
  LayoutAuthenticatedMockInterviewIndexRoute: typeof LayoutAuthenticatedMockInterviewIndexRoute
  LayoutAuthenticatedAnalyzeResultsResultIdRoute: typeof LayoutAuthenticatedAnalyzeResultsResultIdRoute
  LayoutAuthenticatedMockInterviewSessionsSessionIdIndexRoute: typeof LayoutAuthenticatedMockInterviewSessionsSessionIdIndexRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedAnalyzeIndexRoute: LayoutAuthenticatedAnalyzeIndexRoute,
  LayoutAuthenticatedCommunityIndexRoute:
    LayoutAuthenticatedCommunityIndexRoute,
  LayoutAuthenticatedDashboardIndexRoute:
    LayoutAuthenticatedDashboardIndexRoute,
  LayoutAuthenticatedMockInterviewIndexRoute:
    LayoutAuthenticatedMockInterviewIndexRoute,
  LayoutAuthenticatedAnalyzeResultsResultIdRoute:
    LayoutAuthenticatedAnalyzeResultsResultIdRoute,
  LayoutAuthenticatedMockInterviewSessionsSessionIdIndexRoute:
    LayoutAuthenticatedMockInterviewSessionsSessionIdIndexRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAuthIndexRoute: typeof LayoutAuthIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAuthIndexRoute: LayoutAuthIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
