import devicons from "devicon/devicon.json"

const displayNames: Record<string, string> = {
  aarch64: "AArch64",
  adonisjs: "AdonisJS",
  aerospike: "Aerospike",
  aframe: "A-Frame",
  aftereffects: "After Effects",
  akka: "Akka",
  algolia: "Algolia",
  almalinux: "AlmaLinux",
  alpinejs: "Alpine.js",
  amazonwebservices: "AWS",
  anaconda: "Anaconda",
  android: "Android",
  androidstudio: "Android Studio",
  angular: "Angular",
  angularjs: "AngularJS",
  angularmaterial: "Angular Material",
  ansible: "Ansible",
  ansys: "ANSYS",
  antdesign: "Ant Design",
  apache: "Apache",
  apacheairflow: "Apache Airflow",
  apachekafka: "Apache Kafka",
  apachespark: "Apache Spark",
  apex: "Apex",
  apl: "APL",
  apollographql: "Apollo GraphQL",
  appcelerator: "Appcelerator",
  apple: "Apple",
  appwrite: "Appwrite",
  archlinux: "Arch Linux",
  arduino: "Arduino",
  argocd: "Argo CD",
  artixlinux: "Artix Linux",
  astro: "Astro",
  atom: "Atom",
  awk: "AWK",
  axios: "Axios",
  azure: "Azure",
  azuredevops: "Azure DevOps",
  azuresqldatabase: "Azure SQL Database",
  babel: "Babel",
  babylonjs: "Babylon.js",
  backbonejs: "Backbone.js",
  ballerina: "Ballerina",
  bamboo: "Bamboo",
  bash: "Bash",
  bazel: "Bazel",
  beats: "Beats",
  behance: "Behance",
  bevyengine: "Bevy Engine",
  biome: "Biome",
  bitbucket: "Bitbucket",
  blazor: "Blazor",
  blender: "Blender",
  bootstrap: "Bootstrap",
  bower: "Bower",
  browserstack: "BrowserStack",
  bulma: "Bulma",
  bun: "Bun",
  c: "C",
  cairo: "Cairo",
  cakephp: "CakePHP",
  canva: "Canva",
  capacitor: "Capacitor",
  carbon: "Carbon",
  cassandra: "Cassandra",
  centos: "CentOS",
  ceylon: "Ceylon",
  chakraui: "Chakra UI",
  chartjs: "Chart.js",
  chrome: "Chrome",
  circleci: "CircleCI",
  clarity: "Clarity",
  clickhouse: "ClickHouse",
  clion: "CLion",
  clojure: "Clojure",
  clojurescript: "ClojureScript",
  cloudflare: "Cloudflare",
  cloudflareworkers: "Cloudflare Workers",
  cloudrun: "Cloud Run",
  cmake: "CMake",
  cobol: "COBOL",
  codeac: "Codeac",
  codecov: "Codecov",
  codeigniter: "CodeIgniter",
  codepen: "CodePen",
  coffeescript: "CoffeeScript",
  composer: "Composer",
  confluence: "Confluence",
  consul: "Consul",
  contao: "Contao",
  corejs: "core-js",
  cosmosdb: "Cosmos DB",
  couchbase: "Couchbase",
  couchdb: "CouchDB",
  cpanel: "cPanel",
  cplusplus: "C++",
  crystal: "Crystal",
  csharp: "C#",
  css3: "CSS3",
  cucumber: "Cucumber",
  cypressio: "Cypress",
  d3js: "D3.js",
  dart: "Dart",
  datadog: "Datadog",
  datagrip: "DataGrip",
  dataspell: "DataSpell",
  datatables: "DataTables",
  dbeaver: "DBeaver",
  debian: "Debian",
  delphi: "Delphi",
  denojs: "Deno",
  detaspace: "Deta Space",
  devicon: "Devicon",
  digitalocean: "DigitalOcean",
  discloud: "DisCloud",
  discordjs: "Discord.js",
  django: "Django",
  djangorest: "Django REST",
  docker: "Docker",
  doctrine: "Doctrine",
  "dot-net": ".NET",
  dotnetcore: ".NET Core",
  dovecot: "Dovecot",
  dreamweaver: "Dreamweaver",
  dropwizard: "Dropwizard",
  drupal: "Drupal",
  duckdb: "DuckDB",
  dyalog: "Dyalog",
  dynamodb: "DynamoDB",
  dynatrace: "Dynatrace",
  eclipse: "Eclipse",
  ecto: "Ecto",
  elasticsearch: "Elasticsearch",
  electron: "Electron",
  eleventy: "Eleventy",
  elixir: "Elixir",
  elm: "Elm",
  emacs: "Emacs",
  embeddedc: "Embedded C",
  ember: "Ember.js",
  entityframeworkcore: "Entity Framework Core",
  envoy: "Envoy",
  erlang: "Erlang",
  eslint: "ESLint",
  expo: "Expo",
  express: "Express",
  facebook: "Facebook",
  fastapi: "FastAPI",
  fastify: "Fastify",
  faunadb: "FaunaDB",
  feathersjs: "Feathers.js",
  fedora: "Fedora",
  fiber: "Fiber",
  figma: "Figma",
  filamentphp: "Filament PHP",
  filezilla: "FileZilla",
  firebase: "Firebase",
  firebird: "Firebird",
  firefox: "Firefox",
  flask: "Flask",
  flutter: "Flutter",
  forgejo: "Forgejo",
  fortran: "Fortran",
  foundation: "Foundation",
  framermotion: "Framer Motion",
  framework7: "Framework7",
  fsharp: "F#",
  fusion: "Fusion",
  gardener: "Gardener",
  gatling: "Gatling",
  gatsby: "Gatsby",
  gazebo: "Gazebo",
  gcc: "GCC",
  gentoo: "Gentoo",
  ghost: "Ghost",
  gimp: "GIMP",
  git: "Git",
  gitbook: "GitBook",
  github: "GitHub",
  githubactions: "GitHub Actions",
  githubcodespaces: "GitHub Codespaces",
  gitkraken: "GitKraken",
  gitlab: "GitLab",
  gitpod: "Gitpod",
  gitter: "Gitter",
  gleam: "Gleam",
  glitch: "Glitch",
  go: "Go",
  godot: "Godot",
  goland: "GoLand",
  google: "Google",
  googlecloud: "Google Cloud",
  googlecolab: "Google Colab",
  gradle: "Gradle",
  grafana: "Grafana",
  grails: "Grails",
  graphql: "GraphQL",
  groovy: "Groovy",
  grpc: "gRPC",
  grunt: "Grunt",
  gulp: "Gulp",
  hadoop: "Hadoop",
  handlebars: "Handlebars",
  harbor: "Harbor",
  hardhat: "Hardhat",
  harvester: "Harvester",
  haskell: "Haskell",
  haxe: "Haxe",
  helm: "Helm",
  heroku: "Heroku",
  hibernate: "Hibernate",
  homebrew: "Homebrew",
  hoppscotch: "Hoppscotch",
  html5: "HTML5",
  htmx: "htmx",
  hugo: "Hugo",
  hyperv: "Hyper-V",
  ie10: "IE 10",
  ifttt: "IFTTT",
  illustrator: "Illustrator",
  inertiajs: "Inertia.js",
  influxdb: "InfluxDB",
  inkscape: "Inkscape",
  insomnia: "Insomnia",
  intellij: "IntelliJ IDEA",
  ionic: "Ionic",
  jaegertracing: "Jaeger",
  jamstack: "Jamstack",
  jasmine: "Jasmine",
  java: "Java",
  javascript: "JavaScript",
  jeet: "Jeet",
  jekyll: "Jekyll",
  jenkins: "Jenkins",
  jest: "Jest",
  jetbrains: "JetBrains",
  jetpackcompose: "Jetpack Compose",
  jhipster: "JHipster",
  jira: "Jira",
  jiraalign: "Jira Align",
  jquery: "jQuery",
  json: "JSON",
  jule: "Jule",
  julia: "Julia",
  junit: "JUnit",
  jupyter: "Jupyter",
  k3os: "k3OS",
  k3s: "K3s",
  k6: "k6",
  kaggle: "Kaggle",
  kaldi: "Kaldi",
  kalilinux: "Kali Linux",
  karatelabs: "Karate Labs",
  karma: "Karma",
  kdeneon: "KDE Neon",
  keras: "Keras",
  kibana: "Kibana",
  knexjs: "Knex.js",
  knockout: "Knockout",
  kotlin: "Kotlin",
  krakenjs: "Kraken.js",
  ktor: "Ktor",
  kubeflow: "Kubeflow",
  kubernetes: "Kubernetes",
  labview: "LabVIEW",
  laminas: "Laminas",
  laravel: "Laravel",
  laraveljetstream: "Laravel Jetstream",
  latex: "LaTeX",
  leetcode: "LeetCode",
  less: "Less",
  libgdx: "libGDX",
  linkedin: "LinkedIn",
  linux: "Linux",
  linuxmint: "Linux Mint",
  liquibase: "Liquibase",
  livewire: "Livewire",
  llvm: "LLVM",
  lodash: "Lodash",
  logstash: "Logstash",
  love2d: "LÖVE 2D",
  lua: "Lua",
  lumen: "Lumen",
  magento: "Magento",
  mapbox: "Mapbox",
  mariadb: "MariaDB",
  markdown: "Markdown",
  materializecss: "Materialize CSS",
  materialui: "Material UI",
  matlab: "MATLAB",
  matplotlib: "Matplotlib",
  mattermost: "Mattermost",
  maven: "Maven",
  maya: "Maya",
  memcached: "Memcached",
  mercurial: "Mercurial",
  meteor: "Meteor",
  microsoftsqlserver: "MS SQL Server",
  minitab: "Minitab",
  mithril: "Mithril",
  mobx: "MobX",
  mocha: "Mocha",
  modx: "MODX",
  moleculer: "Moleculer",
  mongodb: "MongoDB",
  mongoose: "Mongoose",
  monogame: "MonoGame",
  moodle: "Moodle",
  msdos: "MS-DOS",
  mysql: "MySQL",
  nano: "Nano",
  nats: "NATS",
  neo4j: "Neo4j",
  neovim: "Neovim",
  nestjs: "NestJS",
  netbeans: "NetBeans",
  netbox: "NetBox",
  netlify: "Netlify",
  networkx: "NetworkX",
  newrelic: "New Relic",
  nextjs: "Next.js",
  nginx: "Nginx",
  ngrok: "ngrok",
  ngrx: "NgRx",
  nhibernate: "NHibernate",
  nim: "Nim",
  nimble: "Nimble",
  nixos: "NixOS",
  nodejs: "Node.js",
  nodemon: "Nodemon",
  nodered: "Node-RED",
  nodewebkit: "NW.js",
  nomad: "Nomad",
  norg: "Norg",
  notion: "Notion",
  npm: "npm",
  npss: "NPSS",
  nuget: "NuGet",
  numpy: "NumPy",
  nuxt: "Nuxt",
  nuxtjs: "Nuxt.js",
  oauth: "OAuth",
  objectivec: "Objective-C",
  ocaml: "OCaml",
  ohmyzsh: "Oh My Zsh",
  okta: "Okta",
  openal: "OpenAL",
  openapi: "OpenAPI",
  opencl: "OpenCL",
  opencv: "OpenCV",
  opengl: "OpenGL",
  openstack: "OpenStack",
  opensuse: "openSUSE",
  opentelemetry: "OpenTelemetry",
  opera: "Opera",
  oracle: "Oracle",
  ory: "Ory",
  p5js: "p5.js",
  packer: "Packer",
  pandas: "Pandas",
  passport: "Passport",
  perl: "Perl",
  pfsense: "pfSense",
  phalcon: "Phalcon",
  phoenix: "Phoenix",
  photonengine: "Photon Engine",
  photoshop: "Photoshop",
  php: "PHP",
  phpstorm: "PhpStorm",
  pixijs: "PixiJS",
  playwright: "Playwright",
  plotly: "Plotly",
  pm2: "PM2",
  pnpm: "pnpm",
  podman: "Podman",
  poetry: "Poetry",
  polygon: "Polygon",
  portainer: "Portainer",
  postcss: "PostCSS",
  postgresql: "PostgreSQL",
  postman: "Postman",
  powershell: "PowerShell",
  premierepro: "Premiere Pro",
  primeng: "PrimeNG",
  prisma: "Prisma",
  processing: "Processing",
  processwire: "ProcessWire",
  prolog: "Prolog",
  prometheus: "Prometheus",
  protractor: "Protractor",
  proxmox: "Proxmox",
  pug: "Pug",
  pulsar: "Pulsar",
  pulumi: "Pulumi",
  puppeteer: "Puppeteer",
  purescript: "PureScript",
  putty: "PuTTY",
  pycharm: "PyCharm",
  pypi: "PyPI",
  pyscript: "PyScript",
  pytest: "pytest",
  python: "Python",
  pytorch: "PyTorch",
  qodana: "Qodana",
  qt: "Qt",
  qtest: "qTest",
  quarkus: "Quarkus",
  quasar: "Quasar",
  qwik: "Qwik",
  r: "R Langugage",
  rabbitmq: "RabbitMQ",
  racket: "Racket",
  radstudio: "RAD Studio",
  rails: "Rails",
  railway: "Railway",
  rancher: "Rancher",
  raspberrypi: "Raspberry Pi",
  reach: "Reach",
  react: "React",
  reactbootstrap: "React Bootstrap",
  reactnative: "React Native",
  reactnavigation: "React Navigation",
  reactrouter: "React Router",
  readthedocs: "Read the Docs",
  realm: "Realm",
  rect: "Rect",
  redhat: "Red Hat",
  redis: "Redis",
  redux: "Redux",
  reflex: "Reflex",
  remix: "Remix",
  renpy: "Ren'Py",
  replit: "Replit",
  rexx: "Rexx",
  rider: "Rider",
  rocksdb: "RocksDB",
  rockylinux: "Rocky Linux",
  rollup: "Rollup",
  ros: "ROS",
  rspec: "RSpec",
  rstudio: "RStudio",
  ruby: "Ruby",
  rubymine: "RubyMine",
  rust: "Rust",
  rxjs: "RxJS",
  safari: "Safari",
  salesforce: "Salesforce",
  sanity: "Sanity",
  sass: "Sass",
  scala: "Scala",
  scalingo: "Scalingo",
  scikitlearn: "scikit-learn",
  sdl: "SDL",
  selenium: "Selenium",
  sema: "Sema",
  sentry: "Sentry",
  sequelize: "Sequelize",
  shopware: "Shopware",
  shotgrid: "ShotGrid",
  sketch: "Sketch",
  slack: "Slack",
  socketio: "Socket.IO",
  solidity: "Solidity",
  solidjs: "SolidJS",
  sonarqube: "SonarQube",
  sourceengine: "Source Engine",
  sourcetree: "Sourcetree",
  spack: "Spack",
  spicedb: "SpiceDB",
  splunk: "Splunk",
  spring: "Spring",
  spss: "SPSS",
  spyder: "Spyder",
  sqlalchemy: "SQLAlchemy",
  sqldeveloper: "SQL Developer",
  sqlite: "SQLite",
  ssh: "SSH",
  stackblitz: "StackBlitz",
  stackoverflow: "Stack Overflow",
  stata: "Stata",
  stenciljs: "Stencil.js",
  storybook: "Storybook",
  streamlit: "Streamlit",
  styledcomponents: "styled-components",
  stylus: "Stylus",
  subversion: "Subversion",
  sulu: "Sulu",
  supabase: "Supabase",
  surrealdb: "SurrealDB",
  svelte: "Svelte",
  svgo: "SVGO",
  swagger: "Swagger",
  swift: "Swift",
  swiper: "Swiper",
  symfony: "Symfony",
  tailwindcss: "Tailwind CSS",
  talos: "Talos",
  tauri: "Tauri",
  teleport: "Teleport",
  tensorflow: "TensorFlow",
  terraform: "Terraform",
  terramate: "Terramate",
  tex: "TeX",
  thealgorithms: "The Algorithms",
  threedsmax: "3ds Max",
  threejs: "Three.js",
  thymeleaf: "Thymeleaf",
  titaniumsdk: "Titanium SDK",
  tmux: "tmux",
  tomcat: "Tomcat",
  tortoisegit: "TortoiseGit",
  towergit: "Tower",
  traefikmesh: "Traefik Mesh",
  traefikproxy: "Traefik Proxy",
  travis: "Travis CI",
  trello: "Trello",
  trpc: "tRPC",
  turbo: "Turbo",
  twilio: "Twilio",
  twitter: "Twitter",
  typescript: "TypeScript",
  typo3: "TYPO3",
  ubuntu: "Ubuntu",
  unifiedmodelinglanguage: "UML",
  unity: "Unity",
  unix: "Unix",
  unrealengine: "Unreal Engine",
  uwsgi: "uWSGI",
  v8: "V8",
  vaadin: "Vaadin",
  vagrant: "Vagrant",
  vala: "Vala",
  vault: "Vault",
  veevalidate: "VeeValidate",
  vercel: "Vercel",
  vertx: "Vert.x",
  vim: "Vim",
  visualbasic: "Visual Basic",
  visualstudio: "Visual Studio",
  vite: "Vite",
  vitejs: "Vite",
  vitess: "Vitess",
  vitest: "Vitest",
  vscode: "VS Code",
  vscodium: "VSCodium",
  vsphere: "vSphere",
  vuejs: "Vue.js",
  vuestorefront: "Vue Storefront",
  vuetify: "Vuetify",
  vulkan: "Vulkan",
  vyper: "Vyper",
  waku: "Waku",
  wasm: "WebAssembly",
  web3js: "Web3.js",
  webflow: "Webflow",
  webgpu: "WebGPU",
  weblate: "Weblate",
  webpack: "webpack",
  webstorm: "WebStorm",
  windows11: "Windows 11",
  windows8: "Windows 8",
  wolfram: "Wolfram",
  woocommerce: "WooCommerce",
  wordpress: "WordPress",
  xamarin: "Xamarin",
  xcode: "Xcode",
  xd: "Adobe XD",
  xml: "XML",
  yaml: "YAML",
  yarn: "Yarn",
  yii: "Yii",
  yugabytedb: "YugabyteDB",
  yunohost: "YunoHost",
  zend: "Zend",
  zig: "Zig",
  zsh: "Zsh",
  zustand: "Zustand",
}

export const skillSuggestions = devicons.map((icon) => ({
  label: displayNames[icon.name],
  value: icon.name,
}))
